apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "app_presente"
  SECRET_KEY: "1234566778"
  REDIS_PASSWORD: "redis"
