apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-presente-back
  namespace: stage-app-presente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-presente-back
  template:
    metadata:
      labels:
        app: app-presente-back
    spec:
      containers:
      - name: app-presente-back
        image: ${DOCKER_IMAGE}:${COMMIT_SHA}
        ports:
        - containerPort: 8000
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@app-presente-db-service.stage-app-presente.svc.cluster.local/app_presente"
        - name: REDIS_HOST
          value: "app-presente-redis.stage-app-presente.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
