apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-presente-back
  namespace: stage-app-presente
  labels:
    app: app-presente-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-presente-back
  template:
    metadata:
      labels:
        app: app-presente-back
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app-presente-back
          image: guilherme310402/app_presente_backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-presente-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
