apiVersion: v1
kind: Service
metadata:
  name: app-presente-back-service
  namespace: stage-app-presente
spec:
  selector:
    app: app-presente-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
