name: Backend CI/CD - GCP Kubernetes

on:
  push:
    branches: [master, dev, 'release/**']
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Vkhn2W3LudKzzis
          POSTGRES_DB: app_presente
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest redis

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Initialize Database and Insert Test User
        env:
          PGPASSWORD: Vkhn2W3LudKzzis
        run: |
          psql -h localhost -p 5432 -U postgres -d app_presente -c "CREATE TABLE IF NOT EXISTS usuario (id_usuario SERIAL PRIMARY KEY, login VARCHAR(255), senha VARCHAR(255), nome VARCHAR(255), cargo VARCHAR(255), id_secretaria INTEGER);"
          psql -h localhost -p 5432 -U postgres -d app_presente -c "INSERT INTO usuario (id_usuario, login, senha, nome, cargo, id_secretaria) VALUES (9999, 'addda', 'teste123', 'Test User', 'Secretaria', 70) ON CONFLICT (id_usuario) DO NOTHING;"

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        env: [production, stage]
    env:
      PROJECT_ID: ${{ matrix.env == 'production' && 'app-chamada-5706' || 'app-chamada-stage' }}
      CLUSTER_NAME: ${{ matrix.env == 'production' && 'app-prod-fa395f7c' || 'app-chamada-stage' }}
      GKE_ZONE: ${{ matrix.env == 'production' && 'us-central1-a' || 'us-west1-a' }}
      NAMESPACE: ${{ matrix.env == 'production' && 'app-chamada-production' || 'stage-app-presente' }}
      DOCKER_IMAGE: guilherme310402/app_presente_back
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ matrix.env == 'production' && secrets.GOOGLE_CLOUD_KEYS || secrets.GCP_CREDENTIALS_JSON_STAGE }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          COMMIT_SHA=${{ github.sha }}
          docker build -t $DOCKER_IMAGE:$COMMIT_SHA .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $DOCKER_IMAGE:$COMMIT_SHA
          docker tag $DOCKER_IMAGE:$COMMIT_SHA $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:latest

  deploy-stage:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'
    env:
      PROJECT_ID: app-chamada-stage
      CLUSTER_NAME: app-chamada-stage
      GKE_ZONE: us-west1-a
      NAMESPACE: stage-app-presente
      DOCKER_IMAGE: guilherme310402/app_presente_back
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON_STAGE }}

      - name: Set up Cloud SDK and kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: 'kubectl'

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.GKE_ZONE }} \
            --project ${{ env.PROJECT_ID }}

      - name: Apply Service & Ingress
        run: |
          kubectl apply -f backend-service.yaml
          kubectl apply -f backend-ingress.yaml

      - name: Deploy updated image
        run: |
          COMMIT_SHA=${{ github.sha }}
          kubectl set image deployment/app-presente-back -n ${{ env.NAMESPACE }} \
            app-presente-back=${{ env.DOCKER_IMAGE }}:$COMMIT_SHA

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/app-presente-back \
            -n ${{ env.NAMESPACE }} --timeout=300s

  release-notification:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: hch0kgrxx@mozmail.com
          password: ${{ secrets.EMAIL_PASS }}
          subject: "🚀 Nova versão em pré-produção disponível"
          to: saler.cez@gmail.com
          from: "Presente CI/CD <hch0kgrxx@mozmail.com>"
          html_body: |
            <h2>Nova versão em pré-produção</h2>
            <p>Branch: <strong>${{ github.ref_name }}</strong></p>
            <p>Imagem: <strong>${{ env.DOCKER_IMAGE }}:latest</strong></p>
            <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">Ver execução</a></p>